# Generated by Django 4.2.7 on 2025-11-29 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servers", "0003_remove_server_deployment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Agent Token"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(max_length=64, verbose_name="加密密钥"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("error", "错误"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Agent版本"
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后心跳时间"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "server",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent",
                        to="servers.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agent",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=255, verbose_name="命令")),
                ("args", models.JSONField(default=list, verbose_name="参数")),
                (
                    "timeout",
                    models.IntegerField(default=300, verbose_name="超时时间（秒）"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="agents.agent",
                        verbose_name="Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent命令",
                "verbose_name_plural": "Agent命令",
                "ordering": ["-created_at"],
            },
        ),
    ]
