# Generated by Django 4.2.7 on 2025-11-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="heartbeat_mode",
            field=models.CharField(
                choices=[
                    ("push", "推送模式（Agent主动推送）"),
                    ("pull", "拉取模式（中心平台主动拉取）"),
                ],
                default="push",
                max_length=20,
                verbose_name="心跳模式",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_check",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后检查时间（拉取模式）"
            ),
        ),
    ]
