# Generated by Django 4.2.7 on 2025-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_add_command_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Agent",
                "verbose_name_plural": "Agent",
            },
        ),
        migrations.RemoveField(
            model_name="agent",
            name="secret_key",
        ),
        migrations.AlterField(
            model_name="agent",
            name="heartbeat_mode",
            field=models.CharField(
                choices=[("push", "推送模式"), ("pull", "拉取模式")],
                default="push",
                max_length=10,
                verbose_name="心跳模式",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[("online", "在线"), ("offline", "离线")],
                default="offline",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="token",
            field=models.CharField(max_length=64, unique=True, verbose_name="Token"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="版本"
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="args",
            field=models.JSONField(blank=True, default=list, verbose_name="参数"),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("running", "执行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
