# Generated by Django 4.2.7 on 2025-11-30 08:54

from django.db import migrations, models
import secrets


def generate_secret_keys(apps, schema_editor):
    """为现有Agent生成secret_key"""
    Agent = apps.get_model('agents', 'Agent')
    for agent in Agent.objects.filter(secret_key__isnull=True):
        agent.secret_key = secrets.token_urlsafe(32)
        agent.save(update_fields=['secret_key'])


def reverse_generate_secret_keys(apps, schema_editor):
    """回滚时不需要操作"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_alter_agent_options_remove_agent_secret_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="secret_key",
            field=models.CharField(
                blank=True,
                help_text="用于Agent通信加密的密钥",
                max_length=255,
                null=True,
                verbose_name="加密密钥",
            ),
        ),
        migrations.RunPython(generate_secret_keys, reverse_generate_secret_keys),
    ]
