# Generated by Django 4.2.7 on 2025-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_add_web_service_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="web_service_enabled",
            field=models.BooleanField(
                default=True,
                help_text="是否启用Agent Web服务模式（新架构）",
                verbose_name="启用Web服务",
            ),
        ),
    ]
