# Generated by Django 4.2.7 on 2025-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_add_rpc_support_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="rpc_path",
            field=models.CharField(
                blank=True,
                help_text="RPC随机路径（用于路径混淆，保障安全，由服务器在部署时分配）",
                max_length=64,
                verbose_name="RPC随机路径",
            ),
        ),
    ]
