# Generated by Django 4.2.7 on 2025-12-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0012_agent_rpc_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="certificate_content",
            field=models.TextField(
                blank=True,
                help_text="SSL证书内容（PEM格式），存储在服务器端",
                null=True,
                verbose_name="证书内容",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="private_key_content",
            field=models.TextField(
                blank=True,
                help_text="SSL私钥内容（PEM格式），存储在服务器端",
                null=True,
                verbose_name="私钥内容",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="verify_ssl",
            field=models.BooleanField(
                default=False,
                help_text="是否验证Agent的SSL证书（默认False，因为使用自签名证书）",
                verbose_name="验证SSL证书",
            ),
        ),
    ]
