# Generated by Django 4.2.7 on 2025-12-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0013_add_certificate_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="heartbeat_mode",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="last_check",
        ),
    ]
