# Generated by Django 4.2.7 on 2025-11-29 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="订阅名称")),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="订阅Token"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("v2ray", "V2Ray"), ("clash", "Clash")],
                        default="v2ray",
                        max_length=20,
                        verbose_name="订阅格式",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "订阅",
                "verbose_name_plural": "订阅",
                "ordering": ["-created_at"],
            },
        ),
    ]
