# Generated by Django 4.2.7 on 2025-11-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="proxy_ids",
            field=models.JSONField(default=list, verbose_name="选中的节点ID列表"),
        ),
    ]
