# Generated by Django 4.2.7 on 2025-11-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="deployment_method",
            field=models.CharField(
                choices=[("ssh", "SSH"), ("agent", "Agent"), ("docker", "Docker")],
                default="ssh",
                max_length=20,
                verbose_name="部署方式",
            ),
        ),
    ]
