# Generated by Django 4.2.7 on 2025-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0002_deployment_deployment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deployment",
            name="deployment_method",
        ),
        migrations.AddField(
            model_name="deployment",
            name="connection_method",
            field=models.CharField(
                blank=True,
                choices=[("ssh", "SSH"), ("agent", "Agent")],
                max_length=20,
                null=True,
                verbose_name="连接方式",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="deployment_target",
            field=models.CharField(
                blank=True,
                choices=[("host", "宿主机"), ("docker", "Docker")],
                max_length=20,
                null=True,
                verbose_name="部署目标",
            ),
        ),
    ]
