# Generated by Django 4.2.7 on 2025-11-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0004_alter_deployment_deployment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="deployment_type",
            field=models.CharField(
                choices=[
                    ("xray", "Xray"),
                    ("caddy", "Caddy"),
                    ("both", "Xray + Caddy"),
                    ("full", "一键部署 (Agent + Xray + Caddy)"),
                    ("agent", "Agent"),
                ],
                max_length=20,
                verbose_name="部署类型",
            ),
        ),
    ]
