# Generated by Django 4.2.7 on 2025-12-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0005_add_agent_deployment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "运行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                    ("timeout", "超时"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
