# Generated by Django 4.2.7 on 2025-11-29 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="节点名称")),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("vless", "VLESS"),
                            ("vmess", "VMess"),
                            ("trojan", "Trojan"),
                            ("shadowsocks", "Shadowsocks"),
                        ],
                        max_length=20,
                        verbose_name="协议",
                    ),
                ),
                ("port", models.IntegerField(verbose_name="端口")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP"),
                            ("ws", "WebSocket"),
                            ("grpc", "gRPC"),
                            ("quic", "QUIC"),
                        ],
                        default="tcp",
                        max_length=20,
                        verbose_name="传输方式",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="路径（WS/gRPC）",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="伪装域名"
                    ),
                ),
                (
                    "sni",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SNI"
                    ),
                ),
                (
                    "enable_tls",
                    models.BooleanField(default=True, verbose_name="启用TLS"),
                ),
                (
                    "enable_reality",
                    models.BooleanField(default=False, verbose_name="启用REALITY"),
                ),
                (
                    "reality_public_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="REALITY公钥",
                    ),
                ),
                (
                    "reality_short_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="REALITY Short ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxies",
                        to="servers.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "代理节点",
                "verbose_name_plural": "代理节点",
                "ordering": ["-created_at"],
            },
        ),
    ]
