# Generated by Django 4.2.7 on 2025-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="deployed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="部署时间"),
        ),
        migrations.AddField(
            model_name="proxy",
            name="deployment_log",
            field=models.TextField(blank=True, null=True, verbose_name="部署日志"),
        ),
        migrations.AddField(
            model_name="proxy",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("pending", "待部署"),
                    ("running", "部署中"),
                    ("success", "部署成功"),
                    ("failed", "部署失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="部署状态",
            ),
        ),
    ]
