# Generated by Django 4.2.7 on 2025-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0002_proxy_deployed_at_proxy_deployment_log_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proxy",
            name="enable_reality",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="enable_tls",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="host",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="path",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="reality_public_key",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="reality_short_id",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="sni",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="transport",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="uuid",
        ),
        migrations.AddField(
            model_name="proxy",
            name="down",
            field=models.BigIntegerField(default=0, verbose_name="下载流量（字节）"),
        ),
        migrations.AddField(
            model_name="proxy",
            name="enable",
            field=models.BooleanField(default=True, verbose_name="启用"),
        ),
        migrations.AddField(
            model_name="proxy",
            name="expiry_time",
            field=models.BigIntegerField(
                default=0, verbose_name="到期时间（时间戳），0表示永不到期"
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="listen",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="监听IP，留空使用默认",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="settings",
            field=models.TextField(default="{}", verbose_name="协议设置（JSON字符串）"),
        ),
        migrations.AddField(
            model_name="proxy",
            name="sniffing",
            field=models.TextField(default="{}", verbose_name="嗅探设置（JSON字符串）"),
        ),
        migrations.AddField(
            model_name="proxy",
            name="stream_settings",
            field=models.TextField(default="{}", verbose_name="传输设置（JSON字符串）"),
        ),
        migrations.AddField(
            model_name="proxy",
            name="tag",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="标签"
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="total",
            field=models.BigIntegerField(
                default=0, verbose_name="总流量限制（字节），0表示不限制"
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="up",
            field=models.BigIntegerField(default=0, verbose_name="上传流量（字节）"),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="port",
            field=models.IntegerField(unique=True, verbose_name="端口"),
        ),
    ]
