# Generated by Django 4.2.7 on 2025-12-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0005_caddyfilehistory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="caddyfilehistory",
            new_name="proxies_cad_created_3af333_idx",
            old_name="proxies_cad_created_idx",
        ),
    ]
