# Generated by Django 4.2.7 on 2025-12-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_cloudflareorigincertificate"),
        (
            "proxies",
            "0006_rename_proxies_cad_created_idx_proxies_cad_created_3af333_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="agent_domain",
            field=models.CharField(
                blank=True,
                help_text="自动分配的域名，如 agent-随机10个字符.example.com",
                max_length=255,
                null=True,
                verbose_name="Agent 域名",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="certificate_path",
            field=models.CharField(
                blank=True,
                help_text="证书文件在服务器上的路径",
                max_length=500,
                null=True,
                verbose_name="证书路径",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="cloudflare_cert_id",
            field=models.CharField(
                blank=True,
                help_text="Cloudflare 源证书 ID",
                max_length=100,
                null=True,
                verbose_name="Cloudflare 证书 ID",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="cloudflare_zone",
            field=models.ForeignKey(
                blank=True,
                help_text="使用的 Cloudflare 域名",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.cloudflarezone",
                verbose_name="Cloudflare Zone",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="dns_record",
            field=models.OneToOneField(
                blank=True,
                help_text="关联的 Cloudflare DNS 记录",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proxy",
                to="settings.cloudflarednsrecord",
                verbose_name="DNS 记录",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="private_key_path",
            field=models.CharField(
                blank=True,
                help_text="私钥文件在服务器上的路径",
                max_length=500,
                null=True,
                verbose_name="私钥路径",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="use_cloudflare_cert",
            field=models.BooleanField(
                default=False,
                help_text="是否使用 Cloudflare 源证书（仅适用于代理模式）",
                verbose_name="使用 Cloudflare 源证书",
            ),
        ),
    ]
