# Generated by Django 4.2.7 on 2025-11-29 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="服务器名称")),
                ("host", models.CharField(max_length=255, verbose_name="主机地址")),
                ("port", models.IntegerField(default=22, verbose_name="SSH端口")),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="SSH用户名"),
                ),
                (
                    "password",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            blank=True,
                            max_length=255,
                            null=True,
                            verbose_name="SSH密码",
                        )
                    ),
                ),
                (
                    "private_key",
                    django_cryptography.fields.encrypt(
                        models.TextField(blank=True, null=True, verbose_name="SSH私钥")
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "不活跃"),
                            ("error", "错误"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_check",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后检查时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务器",
                "verbose_name_plural": "服务器",
                "ordering": ["-created_at"],
            },
        ),
    ]
