# Generated by Django 4.2.7 on 2025-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_server_deployment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="deployment_method",
        ),
        migrations.AddField(
            model_name="server",
            name="connection_method",
            field=models.CharField(
                choices=[("ssh", "SSH"), ("agent", "Agent")],
                default="ssh",
                max_length=20,
                verbose_name="连接方式",
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="deployment_target",
            field=models.CharField(
                choices=[("host", "宿主机"), ("docker", "Docker")],
                default="host",
                max_length=20,
                verbose_name="部署目标",
            ),
        ),
    ]
