# Generated by Django 4.2.7 on 2025-11-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_remove_server_deployment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="agent_connect_host",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Agent连接地址"
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="agent_connect_port",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Agent连接端口"
            ),
        ),
    ]
