# Generated by Django 4.2.7 on 2025-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0005_add_password_and_ssh_key_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="connection_method",
            field=models.CharField(
                choices=[("ssh", "SSH"), ("agent", "Agent")],
                default="agent",
                max_length=20,
                verbose_name="连接方式",
            ),
        ),
    ]
