# Generated by Django 4.2.7 on 2025-12-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0007_allow_blank_server_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="auto_clear_password_after_agent_install",
            field=models.BooleanField(
                default=True, verbose_name="安装Agent后自动清除密码"
            ),
        ),
    ]
