# Generated by Django 4.2.7 on 2025-11-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="MyX - 科学技术管理平台",
                        max_length=200,
                        verbose_name="网站标题",
                    ),
                ),
                (
                    "site_subtitle",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="网站副标题",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "应用设置",
                "verbose_name_plural": "应用设置",
            },
        ),
    ]
