# Generated by Django 4.2.7 on 2025-11-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="site_icon",
            field=models.TextField(
                blank=True, default="", verbose_name="网站图标（SVG）"
            ),
        ),
    ]
