# Generated by Django 4.2.7 on 2025-12-04 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("settings", "0006_cloudflarezone_cloudflarednsrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudflareOriginCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_id",
                    models.CharField(
                        help_text="Cloudflare 证书 ID",
                        max_length=100,
                        unique=True,
                        verbose_name="证书 ID",
                    ),
                ),
                (
                    "hostnames",
                    models.JSONField(
                        default=list,
                        help_text="证书覆盖的域名列表",
                        verbose_name="域名列表",
                    ),
                ),
                (
                    "certificate",
                    models.TextField(
                        help_text="PEM 格式的证书内容", verbose_name="证书内容"
                    ),
                ),
                (
                    "private_key",
                    models.TextField(
                        help_text="PEM 格式的私钥内容", verbose_name="私钥内容"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_certificates",
                        to="settings.cloudflareaccount",
                        verbose_name="Cloudflare 账户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_certificates",
                        to="settings.cloudflarezone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cloudflare 源证书",
                "verbose_name_plural": "Cloudflare 源证书",
                "ordering": ["-created_at"],
            },
        ),
    ]
